### ISSUE TITLE
Pittsburgh, PA trends in marijuana citations and arrests 

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#17]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

After marijuana was decriminalized in Pittsburgh, PA, we are hearing reports that police now have a choice whether to give people a citation under Pittsburgh law or arrest under Allegheny County and PA State law. Are there demographic differences in who is being cited vs. arrested for marijuana possession? Has that changed over time, especially in the context of 2015 legislation to decriminalize marijuana?

> at the time we decided to take this on in 2015, black youth were the ones predominantly being arrested. is that still the case?

- who are the people being arrested?
- what were the numbers in 2015?

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Pittsburgh Bureau of Police

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Marijuana citation and arrest records

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

- https://github.com/Police-Data-Accessibility-Project/caasi-help-desk/issues/34
- https://github.com/Police-Data-Accessibility-Project/caasi-help-desk/issues/35
- https://github.com/Police-Data-Accessibility-Project/caasi-help-desk/issues/36
- https://github.com/Police-Data-Accessibility-Project/caasi-help-desk/issues/37
- https://github.com/Police-Data-Accessibility-Project/caasi-help-desk/issues/45

**Comment by josh-chamberlain** [comment]
Students performed some analysis last semester here: https://github.com/Police-Data-Accessibility-Project/caasi-help-desk/blob/main/mj-decriminalization/analysis/grief%20to%20action/05-marijuana_visualizations.ipynb

This is a great start with helpful analysis, but it's hard to call this request "complete" without a summary of the response.

### Requirements

setup:
- [ ] accept the write access invite to the [caasi-help-desk repository](https://github.com/Police-Data-Accessibility-Project/caasi-help-desk)
- [ ] download and use GitHub Desktop to clone the [caasi-help-desk repository](https://github.com/Police-Data-Accessibility-Project/caasi-help-desk) ([instructions](https://docs.github.com/en/desktop/adding-and-cloning-repositories/cloning-a-repository-from-github-to-github-desktop))
- [ ] use github desktop to make a new branch called something like "mj-summary"
  - this is so that any changes you make are not made to "main" and you can safely experiment
- [ ] publish the branch to GitHub
  - this is a checkpoint to make sure the previous steps worked
- [ ] download Visual Studio Code and use it to open the repository folder you cloned
- [ ] open the mj-decriminalization folder in Visual Studio code

next:
- [ ] review the original request in the folder's README
- [ ] review the published results linked above in Visual Studio code; do the cells of the notebook run properly when you click play? if you make changes, are you able to change/break parts of the notebook by updating code blocks and re-running?
- [ ] comment on this issue with a brief summary (a few sentences) of the existing notebook, whether all the pieces of analysis seem to be there to answer the question, and what additional calculations/charts might be helpful.

**Comment by maxachis** [comment]
> review the published results linked above in Visual Studio code; do the cells of the notebook run properly when you click play? if you make changes, are you able to change/break parts of the notebook by updating code blocks and re-running?

After reviewing it myself, I can confirm there are a few missing puzzles pieces in the existing code. The main entry missing is the portion where they identify (from the WPRDC data they cite), the Marijuana-related arrests and citations, and combine that data together. Instead, that data is hosted in a Google account (which we can't access), and which the original coders then downloaded. 

From a learning standpoint, I think it's more fruitful if we work with the raw code, and clearly define the steps taken to derive that data, so that others can better repeat the steps of Brian's analysis.

**Comment by josh-chamberlain** [comment]
@maxachis 100%. I believe they were derived from the original files and stored there for sharing, but I did not realize they were actually referencing google drive...my fault. We should just keep them in the repo!

**Comment by BBarr-PDAP** [comment]
Attached is the Google Doc that Max and I worked on last week. Thank you, again, Josh, for allowing me to assist on this Issue, and Max for helping me work through this data to analyze it! 

https://docs.google.com/document/d/1iaFJsgaAQpzfMaVLSCI0mNoum6zJ1F7FTTxll5d5ZS0/edit

**Comment by josh-chamberlain** [comment]
@BBarr-PDAP looks like the google doc is private. Unless it's more than a page or two, would you mind just commenting it here?

**Comment by CAASI-Admin** [comment]
@BBarr-PDAP how is progress advancing on this ticket? Josh would like the completion of this ticket by next week so we can begin wireframing the visualizations  next week 10/13.

**Comment by josh-chamberlain** [comment]
To clarify, I was just hoping for the completion of this portion: 

> comments have been added to the outline of a new template file here: https://github.com/Police-Data-Accessibility-Project/caasi-help-desk/pull/29
> - [ ] add code which completes the steps outlined in those comments.
