### ISSUE TITLE
Pennsylvania firearm discharge data

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#57]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Are there numbers of total firearm discharge by county?

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Pennsylvania/Allegheny County

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Data location

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
The City of Pittsburgh Bureau of Police (PBP) and the Allegheny County Department of Human Services (DHS) create [dashboards such as this one](https://tableau.alleghenycounty.us/t/PublicSite/views/CJ_GunViolence_PGH_8-22-17_v2/DataandDefinitions_1?%3Aembed=y&%3AshowAppBanner=false&%3AshowShareOptions=true&%3Adisplay_count=no&%3AshowVizHome=no) that reports data on shots fired from 2012 onward in the city of Pittsburgh. It collects the data from 911 dispatches and can be broken down by year/month and by neighborhood. However, since there is no data county-wide (only within the City of Pittsburgh), and since 911 dispatches for the entire county are not public data, we are not able to replicate this project for the entire county.



It's worth noting [this recent article](https://www.wired.com/story/shotspotter-secret-sensor-locations-leak/) from Wired about some leaked locations of ShotSpotter, which includes many in the Pittsburgh area. ShotSpotter leads to many false alarms, so it may not be a good source of firearm discharges.
