### ISSUE TITLE
Pittsburgh PA Police accreditation 

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#58]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

When does the City of Pittsburgh Police accreditation come up for review? 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Pittsburgh Bureau of Police - PA

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Data location/data selection

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Response from a volunteer:

1. Current status
- According to the PCPA, the Pittsburgh Bureau of Police was [accredited ](https://pcpa.memberclicks.net/accredited-agencies)on 1/10/2013 by the Pennsylvania Law Enforcement Accreditation Commission (PLEAC) which was developed by the Pennsylvania Chiefs of Police in 2001
- Not accredited by the CALEA (Commission on Accreditation for Law Enforcement Agencies), which is a different organization (see [here ](https://www.calea.org/about-us)for more information), according to their 2022 annual [report](https://7a140732.flowpaper.com/CALEAAR2022final/#page=24) 
2. Re-accreditation procedure
- According to the PCPA [website](https://pcpa.memberclicks.net/enrollment), “accreditation status will remain valid for a three-year period with annual reports required”
- “there is a $1,000 annual program maintenance fee for agencies whose Chief is an Active Member of PCPA.   For all others, the annual program maintenance fee is $1,250.  This annual fee does not apply until you become an accredited agency.  This fee is necessary to help defray the direct costs of your subsequent re-accreditation on-site assessments” (from [FAQ ](https://pcpa.memberclicks.net/faq-s)page)
3. Other info:
- Civilians are allowed to be Accreditation Managers (from [FAQ ](https://pcpa.memberclicks.net/faq-s)page)
- Link to [Standards Manual](https://pcpa.memberclicks.net/assets/docs/AccreditationDocuments/Standards%20Manual%20April%202023.pdf)
- In July 2022, WESA published an [article](https://www.wesa.fm/2022-07-01/pittsburgh-police-accreditation-threatened-by-law-to-scale-back-traffic-stops) summarizing how pittsburgh police was threatened by PLEAC that their accreditation would be revoked. The reason was that the city of pittsburgh passed an ordinance that prohibited police from pulling over motorists for minor infractions like a broken brake light, but PLEAC claimed this violated PA’s vehicle code. Essentially, PLEAC said the city of pittsburgh couldn’t override PA’s vehicle code, and this ordinance did that, so PLEAC threatened revocation of the accreditation (for violating their policy of following all state and federal law, including state vehicle codes).
- The ordinance was originally passed as a response to disproportionate enforcement against POC, due to racial bias by police.
- Another [article ](https://www.wesa.fm/politics-government/2023-01-12/pittsburgh-police-resume-secondary-traffic-stops-despite-city-ordinance-against-them)published by WESA in January 2023 said that the accrediation agency ultimately decided against revoking accreditation (It says: “According to Jim Adams, accreditation coordinator for the chiefs association, Pittsburgh was granted a waiver through 2025. He said that while following the ordinance runs afoul of the accreditation standards, “it was no fault of the police department or the police chief.”). However, the pittsburgh police department decided to no longer abide by the ordinance, citing officers’ inability to properly do their jobs.
